In [1]:
import numpy as np

In [9]:
array1 = np.array([1,2,3])
array2 = np.array([
    [1,2,3],
    [2,3,4]
])
array3 = np.array([[1,2,3]])
print(array1.shape, array2.shape, array3.shape)
print(array1.ndim, array2.ndim, array3.ndim)

(3,) (2, 3) (1, 3)
1 2 2


## arange, zeros, ones

In [22]:
print(np.arange(10))
print(np.zeros((3,2), dtype='int32'))
print(np.ones((3,2), dtype='int32'))

[0 1 2 3 4 5 6 7 8 9]
[[0 0]
 [0 0]
 [0 0]]
[[1 1]
 [1 1]
 [1 1]]


## reshape

In [17]:
arr1 = np.arange(10)
print(arr1.reshape(2,5))
# arr1.reshape(3,4) # error
# -1 option
print(arr1.reshape(5,-1))
# 3d
arr1 = np.arange(16)
print(arr1.reshape((2,2,2,2)))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


## indexing
list와 동일

### 1차원

In [27]:
array1d = np.arange(start=1, stop=10)
print(array1d[2])
print(array1d[5:])

3
[6 7 8 9]


### 2차원

In [34]:
array2d = array1d.reshape(3,3)
print(array2d[0,0], array2d[1,1], array2d[2,2])
print(array2d[1:, :2])

1 5 9
[[4 5]
 [7 8]]


### *** remind

In [32]:
array1d_ref = array1d
array1d_val = array1d[:]

### fancy indexing

In [39]:
print(array2d[[0,1],2])
print(array2d[[0,1],[0,1]])
print(array2d[[0,1]])

[3 6]
[1 5]
[[1 2 3]
 [4 5 6]]


### boolean indexing

In [41]:
array1d[array1d > 5]
array2d[array2d > 5]

array([6, 7, 8, 9])

## sort

In [54]:
org_array = np.array([3, 1, 9, 5])

print('원본이 바뀌지 않음: np.array(target)')
print(org_array)
print(np.sort(org_array))

print('------------------')
print('원본이 바뀜: target.sort()')
print(org_array.sort())
print(org_array)

원본이 바뀌지 않음: np.array(target)
[3 1 9 5]
[1 3 5 9]
------------------
원본이 바뀜: target.sort()
None
[1 3 5 9]


### 내림차순(역순정렬)

In [58]:
org_array = np.array([3, 1, 9, 5])
print(np.sort(org_array)[::-1])

[9 5 3 1]


### axis

In [65]:
array2d = np.array([[8, 12],
                   [7, 1]])
print(np.sort(array2d, axis=0)) # row방향, 세로
print(np.sort(array2d, axis=1)) # default, col방향, 가로

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


### argsort

In [68]:
print(np.argsort(org_array))
print(np.argsort(org_array)[::-1])

[1 0 3 2]
[2 3 0 1]


### example

In [72]:
name_arr = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_arr = np.array([78,95,84,98,88])
sort_indices_asc = np.argsort(score_arr)[::-1]
print(sort_indices_asc)
print(name_arr[sort_indices_asc])

[3 1 4 2 0]
['Kate' 'Mike' 'Samuel' 'Sarah' 'John']


## 선형대수 연산

### 내적

In [101]:
a = np.arange(start=1, stop=7)
a = a.reshape(2,3)
b = np.arange(start=7, stop=13)
b = b.reshape(3,2)

print(a)
print(b)
print(np.dot(a,b))

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]


In [87]:
a = np.arange(start=1, stop=5)
a = a.reshape(2,2)
print(a)
print(np.transpose(a))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [103]:
a = np.arange(4).reshape(2, 2)
a_inv = np.linalg.inv(a)
a_d = a.dot(a_inv)

In [104]:
# 대상 * 역행렬 = 단위행렬
# a * a_inv = a_d
print(a)
print(a_d)

# 대상 * 단위행렬 = 대상
print(a.dot(a_d))
# 대상 * 역행렬 = 단위행렬
print(a.dot(a_inv))

[[0 1]
 [2 3]]
[[1. 0.]
 [0. 1.]]
[[0. 1.]
 [2. 3.]]
[[1. 0.]
 [0. 1.]]
