In [12]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [6]:
x_train = torch.FloatTensor([[1], 
                             [2], 
                             [3]]) # 입력
y_train = torch.FloatTensor([[2], 
                             [4], 
                             [6]]) # 레이블 / 클래스

In [8]:
W = torch.zeros(1, requires_grad=True)
W

tensor([0.], requires_grad=True)

In [9]:
b = torch.zeros(1, requires_grad=True)
b

tensor([0.], requires_grad=True)

In [12]:
hypothesis = x_train * W + b
hypothesis

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)

In [14]:
cost = torch.mean((hypothesis - y_train) ** 2)
cost

tensor(18.6667, grad_fn=<MeanBackward0>)

In [15]:
optimizer = optim.SGD([W, b], lr=0.01)

In [16]:
optimizer.zero_grad()
cost.backward()
optimizer.step()

In [29]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 3000 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/3000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/3000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/3000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/3000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/3000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/3000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/3000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/3000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/3000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/3000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/3000 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/3000 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/3000 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/3000 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/3000 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/3000 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/3000 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/3000 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/3000 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/3000 W: 1.997, b: 0.008 Cost: 0.000008

In [3]:
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [4]:
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([w1, w2, w3, b], lr=0.00001)

nb_epochs = 10000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))

Epoch    0/10000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/10000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563634
Epoch  200/10000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497603
Epoch  300/10000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435026
Epoch  400/10000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375730
Epoch  500/10000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319503
Epoch  600/10000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266215
Epoch  700/10000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215693
Epoch  800/10000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167821
Epoch  900/10000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122419
Epoch 1000/10000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079375
Epoch 1100/10000 w1: 0.722 w2: 0.608 w3: 0.680 b: 0.009 Cost: 1.038569
Epoch 1200/10000 w1: 0.727 w2: 0.603 w3: 0.681 b: 0.010 Cost: 0.999893
Epoch 1300/10000 w1: 0.731 w2: 0.599 w3: 0.681 b: 0.010 Cost: 0.963217
Ep

In [5]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [6]:
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 
nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    2/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    3/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    4/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    5/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    6/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    7/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    8/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    9/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch   10/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch   11/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch   12/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch   13/20 hypothesis: tensor([0., 

In [7]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])
model = nn.Linear(3,1)

In [8]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.0335,  0.5347, -0.1827]], requires_grad=True), Parameter containing:
tensor([-0.3583], requires_grad=True)]


In [10]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 
nb_epochs = 3000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/3000 Cost: 2.648077
Epoch  100/3000 Cost: 2.518195
Epoch  200/3000 Cost: 2.395159
Epoch  300/3000 Cost: 2.278622
Epoch  400/3000 Cost: 2.168202
Epoch  500/3000 Cost: 2.063622
Epoch  600/3000 Cost: 1.964560
Epoch  700/3000 Cost: 1.870717
Epoch  800/3000 Cost: 1.781821
Epoch  900/3000 Cost: 1.697598
Epoch 1000/3000 Cost: 1.617857
Epoch 1100/3000 Cost: 1.542277
Epoch 1200/3000 Cost: 1.470711
Epoch 1300/3000 Cost: 1.402906
Epoch 1400/3000 Cost: 1.338680
Epoch 1500/3000 Cost: 1.277836
Epoch 1600/3000 Cost: 1.220218
Epoch 1700/3000 Cost: 1.165608
Epoch 1800/3000 Cost: 1.113896
Epoch 1900/3000 Cost: 1.064907
Epoch 2000/3000 Cost: 1.018478
Epoch 2100/3000 Cost: 0.974521
Epoch 2200/3000 Cost: 0.932881
Epoch 2300/3000 Cost: 0.893435
Epoch 2400/3000 Cost: 0.856060
Epoch 2500/3000 Cost: 0.820659
Epoch 2600/3000 Cost: 0.787125
Epoch 2700/3000 Cost: 0.755350
Epoch 2800/3000 Cost: 0.725255
Epoch 2900/3000 Cost: 0.696751
Epoch 3000/3000 Cost: 0.669738


In [4]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1,1)
    
    def forward(self, x):
        return self.linear(x)

In [5]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [13]:
model = LinearRegressionModel()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000
